### ISSUE TITLE
Styles do not get inherited when working with namespaces!

### ISSUE THREAD

**Issue by AlexVentura** [cle61/arctic_admin#17]
I was trying to create some namespaces apart from the default `/admin` one, following the [documentation](https://activeadmin.info/1-general-configuration.html#namespaces). And now I have the next routes:

***/admin/dashboard*
*/reportmanager/dashboard*
*/customersuccessmanager/dashboard***

So in my `active_admin` initializer file:
```
ActiveAdmin.setup do |config|
  # /reportmanager
  config.namespace :reportmanager do |report_manager|
    report_manager.authentication_method = :authenticate_reportmanager_user!
    report_manager.current_user_method = :current_reportmanager_user
  end
  # /customersuccessmanager
  config.namespace :customersuccessmanager do |customer_success_manager|
    customer_success_manager.authentication_method = :authenticate_customersuccessmanager_user!
    customer_success_manager.current_user_method = :current_customersuccessmanager_user
  end
end
```

When I go to the `admin` namespace the styles work excellent but when I go to any of the other ones some styles seems to crash as in the next picture:
![screen shot 2017-11-02 at 15 59 33](https://user-images.githubusercontent.com/13169164/32359977-5c3b85cc-c017-11e7-9b97-8aaa2ccb4b41.png)

Then digging a little bit more I saw that the problem comes in the classes that the gem sets automatically in the `<body>` tag as shown below:
![screen shot 2017-11-02 at 21 51 32](https://user-images.githubusercontent.com/13169164/32360053-07f547ea-c018-11e7-886d-d5240a8816ab.png)
![screen shot 2017-11-02 at 17 23 25](https://user-images.githubusercontent.com/13169164/32360055-0b59a2c8-c018-11e7-9265-26dacba69dfe.png)
![screen shot 2017-11-02 at 21 52 44](https://user-images.githubusercontent.com/13169164/32360070-328721b8-c018-11e7-8abf-5c51931c14eb.png)

When changing `reportmanager_namespace` or `customersuccessmanager_namespace`class to `admin_namespace` it all works. So, depending on the namespace **ActiveAdmin** creates a special class with the `_namespace` ending and that's why the styles crash when in other namespaces different than `/admin`.

**ArcticAdmin** styles are related to the `admin_namespace` class and do not work with any other:
<img width="1439" alt="screen shot 2017-11-03 at 14 30 53" src="https://user-images.githubusercontent.com/13169164/32394714-a8bd5a7e-c0a3-11e7-90be-962b4de983e6.png">

- Any suggestion how to fix it different than creating my own classes or duplicating the **ArcticAdmin** ones?
- Shouldn't they be automatically generated for each namespace?
🤔

**Comment by cle61** [comment]
Thanks for the repport, i will patch it soon !

**Comment by AlexVentura** [comment]
Great! I hope it comes soon, I need this as soon as it be possible for you! I’ll keep an aye on it!
Thanks!

**Comment by cle61** [comment]
it seen you have an older version of arctic_admin.
The problem was fix here : https://github.com/cle61/arctic_admin/commit/a8b7fab65be3f1211be0dd9417a3be4c351d6170

So use the latest version and say it's all are ok ? 

thanks
