### ISSUE TITLE
Drop down and scrollable sidebar menu

### ISSUE THREAD

**Issue by alifjamaluddin** [cle61/arctic_admin#2]
Can I request for scrollable and drop down sidebar menu for this theme.

**Comment by cle61** [comment]
yep, it's planned, maybe in a few weeks.
if you want to make it yourself, fork my repo and make pull request.

**Comment by cle61** [comment]
done in the v1.2.0

**Comment by bmalets** [comment]
The problem is occurring again in arctic_admin (4.3.1)
