### ISSUE TITLE
Table overflows the white container in the views.

### ISSUE THREAD

**Issue by AlexVentura** [cle61/arctic_admin#23]
When the model has too many attributes the table get wider and overflows the white panel as shown in the picture below.

Any suggestion to fix it? 

![33490442-2a2f072a-d6dd-11e7-92be-15a515e77fa9](https://user-images.githubusercontent.com/13169164/33680907-a37206f6-da88-11e7-928a-f030c41d5490.PNG)

**Comment by cle61** [comment]
Hello,

I have no idea how to resolve this but you can custom your index to remove useless column :
https://activeadmin.info/3-index-pages.html

**Comment by AlexVentura** [comment]
@cle61 Thanks for your answer, but I think all my columns are important to be shown.
Anyway, I think I have _kind of fix_ for this, all make a PR in order for you yo check this out, ok?

**Comment by cle61** [comment]
yeah no problem !
