### ISSUE TITLE
undefined local variable or method `build_sidebar', using branch 2.0

### ISSUE THREAD

**Issue by markselby9** [cle61/arctic_admin#24]
Hi, this issue still exists after using branch 2-0-alpha, it seems to be caused by: https://github.com/cle61/arctic_admin/blob/2-0-alpha/lib/arctic_admin/active_admin/views/pages/bases.rb#L18

![image](https://user-images.githubusercontent.com/3454734/33802591-927ad4b0-ddb5-11e7-8006-6d91577d2ca8.png)
in Gemfile:
![image](https://user-images.githubusercontent.com/3454734/33802626-f9c81a06-ddb5-11e7-9f4c-5c1727ed9c43.png)

referring: https://github.com/cle61/arctic_admin/issues/20

**Comment by markselby9** [comment]
activeadmin version: 
![image](https://user-images.githubusercontent.com/3454734/33802631-16ba2da2-ddb6-11e7-8a94-4675b27340fc.png)

thanks!

**Comment by CarlosIgnacioGo** [comment]
@markselby9 did you find a solution?

**Comment by markselby9** [comment]
@CarlosIgnacioGo Not yet, unless you roll back both versions of activeadmin and arcticadmin so they can align up, which is not an available choice for my project..

**Comment by cle61** [comment]
Hello, sorry i am busy right now..

It's because the file on the next link is not up date ! just update it and make a pull request ;)

https://github.com/cle61/arctic_admin/blob/2-0-alpha/lib/arctic_admin/active_admin/views/pages/bases.rb#L18

**Comment by cle61** [comment]
Hello !
i have updated the branch `2-0-alpha` and remove the monkey patch !
Just add this line to the file `config/application.rb`

```ruby
ActiveAdmin.application.meta_tags = { viewport: 'width=device-width, initial-scale=1' }
```
