### ISSUE TITLE
Batch Actions dropdown opened and button disabled on Index page

### ISSUE THREAD

**Issue by stuart-purr** [cle61/arctic_admin#30]
Have attempted to apply fix as described in [Active Admin issues](https://github.com/activeadmin/activeadmin/issues/4915) but it still doesn't rectify the issue in this theme.

**Comment by stuart-purr** [comment]
fixed, conflict with activeadmin/base - removed //=require activeadmin/base completely from active_admin.js file

**Comment by stuart-purr** [comment]
Custom JS files are not being loaded through arctic_admin/base, although they are if I remove `arctic_admin/base` and revert to `active_admin/base` in the active_admin.js file

**Comment by cle61** [comment]
Which version you use ? activeadmin ? arcticadmin ?

**Comment by stuart-purr** [comment]
arctic_admin (1.4.3), activeadmin (1.1.0)

All I have in my active_admin.js file is
`//= require arctic_admin/base`
`//= require chartkick`

**Comment by stuart-purr** [comment]
@cle61, have you been able to investigate this yet? I've still not found a way to make it work

**Comment by cle61** [comment]
sorry, I do not have a lot of time ...
i am open to any merge request if you find the problem

**Comment by stuart-purr** [comment]
It was a versioning issue - updated from AA 1.1 to 1.2.1 fixed
