### ISSUE TITLE
adapt to work with active admin addons 

### ISSUE THREAD

**Issue by yshr446** [cle61/arctic_admin#31]

**Comment by cle61** [comment]
More info ?

I use activeadmin addons and arctic_admin on my projects

**Comment by yshr446** [comment]
Sorry, when I use `serch_select` input by activeadmin addons, it collapsed styles.

please tell me  how to work arctic_admin and addons together.

**Comment by cle61** [comment]
screenshot ?
Which version you use activeadmin and arctic_admin ?
How you implement the js and css for activeadmin and arctic_admin ?

For exemple: 
```sass
// active_admin.scss
@import "activeadmin_addons/all";
@import "arctic_admin/base";
```

```coffeescript
# active_admin.coffee
#= require arctic_admin/base
#= require activeadmin_addons/all
```

activeadmin (1.1.0)
activeadmin_addons (1.1.2)
arctic_admin (1.3.1)

**Comment by yshr446** [comment]
thanks to your advice, `search_select` work well!
but now `search_select_filter` dosen't show well..

<img width="195" alt="screen shot 2018-02-13 at 23 29 38" src="https://user-images.githubusercontent.com/19199223/36154781-d580ad28-1115-11e8-8249-6aca4bd25e65.png">

my usage:

```
filter :curator_id, as: :search_select_filter,
collection: User.where(user_type: %i[admin partner]).pluck(:name, :id)
```

my versions:
`activeadmin (1.1.0)`
`activeadmin_addons (1.0.1)`
`arctic_admin (1.4.3)`
