### ISSUE TITLE
Cannot read property 'getBoundingClientRect' of undefined

### ISSUE THREAD

**Issue by franciscopinheir** [cle61/arctic_admin#36]
if I'm not at ActiveAdmin and click on the page this happens: Cannot read property 'getBoundingClientRect' of undefined. How do I include '//= require arctic_admin/base' only on activeadmin?

**Comment by cle61** [comment]
Just incluse this line in the file : active_admin.js

You can check this repository for more context https://github.com/cle61/arctic_admin-demo

**Comment by franciscopinheir** [comment]
That's not the problem. I have that line included in the file: active_admin. But when I require that file in application.js that makes the javascript available for the whole project, theres no problem in Admin. But in the froontend of the project doesn't exist any element with the id 'tabs' thats why this error happens.

**Comment by cle61** [comment]
The gem was make only for activeadmin.
Remove the line from application.js

**Comment by franciscopinheir** [comment]
I understand, but how do I include that line only in ActiveAdmin without interfere with the whole project?

**Comment by cle61** [comment]
> Just incluse`//= require arctic_admin/base` in the file : active_admin.js

**Comment by franciscopinheir** [comment]
But how do I require de active_admin.js only for the views of ActiveAdmin?

**Comment by cle61** [comment]
By default, activeadmin load only the active_admin.js file
But you can choose another file in the initializer active_admin.rb
I close the issue, check active_admin for more information

**Comment by JulienCorb** [comment]
Hey @cle61 sorry to get back with that issue, I actually have it too, even though I only included the `//= require arctic_admin/base` in active_admin.js; 

The thing is, I have `//= require_tree .` in application.js which make it load the content of active_admin.js anywhere in my app, not only in active admin. 

Is there a way to change this ?

**Comment by cle61** [comment]
hello @JulienCorb,
i think use `//= require_tree .` in application.js is bad practice (https://www.quora.com/Is-require-tree-a-bad-practice-in-Ruby-on-Rails)
i think you should remove the line `//= require_tree .` and include only the js file you need for your application.js

**Comment by JulienCorb** [comment]
ok got it thank you very much @cle61 ! I finally went with an alternative solution to this problem: 

I simply moved active_admin.js in vendor/assets/javascripts/. Now active_admin.js only loads when I'm in active admin.

**Comment by rafaltrojanowski** [comment]
https://github.com/activeadmin/activeadmin/issues/3819#issuecomment-351377822
