### ISSUE TITLE
Menu Item on hover is changing style

### ISSUE THREAD

**Issue by gabrieldesar** [cle61/arctic_admin#42]
Hi!

After last update (1.5.1) on item hover all the menu items are changing their font type and start flickering.

Above an image of the issue 

![image](https://user-images.githubusercontent.com/3300872/44726241-ac34b680-aaad-11e8-8533-9484b380dfc0.png)

**Comment by cle61** [comment]
yes i'm on it 😢

**Comment by cle61** [comment]
Done ! use the version 1.5.2
