### ISSUE TITLE
Invalid username / password for demo

### ISSUE THREAD

**Issue by alienxp03** [cle61/arctic_admin#5]
I'm trying to login to the demo site using admin@example.com / password, but I'm getting wrong credential errors. Credentials have been changed?

**Comment by cle61** [comment]
yep, someone remove adminuser ...

**Comment by zenati** [comment]
@cle61 Demo not working again, sorry. Can you may be make sure to remove :destroy, :update from Admin so that nobody changes it again. Thank you.

**Comment by cle61** [comment]
done, thanks
